name: Create a build pipeline

on:
    workflow_dispatch:
    push:
        branches:
          - main

jobs:
    node-build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18,20,22]
    
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Setup node
            uses: actions/node-version@v3
            with:
                node-version: ${{ matrix.node-version }}
          
          - name: Install node version
            run: npm ci

          - name: Testing node suite
            run: npm test